production:
  access_key_id: AKIAJV7TZXSHUWIKGMRA
  secret_access_key: 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
  bucket: media.serendipity

development:
  access_key_id: AKIAJV7TZXSHUWIKGMRA
  secret_access_key: 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
  bucket: development.serendipity

test:
  access_key_id: AKIAJV7TZXSHUWIKGMRA
  secret_access_key: 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
  bucket: development.serendipity
