require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BagtypesController do

  # This should return the minimal set of attributes required to create a valid
  # Bagtype. As you add validations to Bagtype, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  before(:each) do
    log_in_test Factory(:admin)
  end

  describe "GET index" do
    it "assigns all bagtypes as @bagtypes" do
      bagtype = Bagtype.create! valid_attributes
      get :index
      assigns(:bagtypes).should eq([bagtype])
    end
  end

  describe "GET show" do
    it "assigns the requested bagtype as @bagtype" do
      bagtype = Bagtype.create! valid_attributes
      get :show, :id => bagtype.id.to_s
      assigns(:bagtype).should eq(bagtype)
    end
  end

  describe "GET new" do
    it "assigns a new bagtype as @bagtype" do
      get :new
      assigns(:bagtype).should be_a_new(Bagtype)
    end
  end

  describe "GET edit" do
    it "assigns the requested bagtype as @bagtype" do
      bagtype = Bagtype.create! valid_attributes
      get :edit, :id => bagtype.id.to_s
      assigns(:bagtype).should eq(bagtype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bagtype" do
        expect {
          post :create, :bagtype => valid_attributes
        }.to change(Bagtype, :count).by(1)
      end

      it "assigns a newly created bagtype as @bagtype" do
        post :create, :bagtype => valid_attributes
        assigns(:bagtype).should be_a(Bagtype)
        assigns(:bagtype).should be_persisted
      end

      it "redirects to the created bagtype" do
        post :create, :bagtype => valid_attributes
        response.should redirect_to(Bagtype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bagtype as @bagtype" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bagtype.any_instance.stub(:save).and_return(false)
        post :create, :bagtype => {}
        assigns(:bagtype).should be_a_new(Bagtype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bagtype.any_instance.stub(:save).and_return(false)
        post :create, :bagtype => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bagtype" do
        bagtype = Bagtype.create! valid_attributes
        # Assuming there are no other bagtypes in the database, this
        # specifies that the Bagtype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bagtype.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => bagtype.id, :bagtype => {'these' => 'params'}
      end

      it "assigns the requested bagtype as @bagtype" do
        bagtype = Bagtype.create! valid_attributes
        put :update, :id => bagtype.id, :bagtype => valid_attributes
        assigns(:bagtype).should eq(bagtype)
      end

      it "redirects to the bagtype" do
        bagtype = Bagtype.create! valid_attributes
        put :update, :id => bagtype.id, :bagtype => valid_attributes
        response.should redirect_to(bagtype)
      end
    end

    describe "with invalid params" do
      it "assigns the bagtype as @bagtype" do
        bagtype = Bagtype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bagtype.any_instance.stub(:save).and_return(false)
        put :update, :id => bagtype.id.to_s, :bagtype => {}
        assigns(:bagtype).should eq(bagtype)
      end

      it "re-renders the 'edit' template" do
        bagtype = Bagtype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bagtype.any_instance.stub(:save).and_return(false)
        put :update, :id => bagtype.id.to_s, :bagtype => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bagtype" do
      bagtype = Bagtype.create! valid_attributes
      expect {
        delete :destroy, :id => bagtype.id.to_s
      }.to change(Bagtype, :count).by(-1)
    end

    it "redirects to the bagtypes list" do
      bagtype = Bagtype.create! valid_attributes
      delete :destroy, :id => bagtype.id.to_s
      response.should redirect_to(bagtypes_url)
    end
  end

end
