require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItemDescriptionsController do


  # This should return the minimal set of attributes required to create a valid
  # ItemDescription. As you add validations to ItemDescription, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:name => 'Test Item Description', :description => 'Some stuff', :rarity => 'rare', :image_id => 1}
  end

  before(:each) do
    log_in_test(Factory(:admin))
  end

  describe "GET index" do
    it "assigns all item_descriptions as @item_descriptions" do
      item_description = ItemDescription.create! valid_attributes
      get :index
      assigns(:item_descriptions).should eq([item_description])
    end
  end

  describe "GET show" do
    it "assigns the requested item_description as @item_description" do
      item_description = ItemDescription.create! valid_attributes
      get :show, :id => item_description.id.to_s
      assigns(:item_description).should eq(item_description)
    end
  end

  describe "GET new" do
    it "assigns a new item_description as @item_description" do
      get :new
      assigns(:item_description).should be_a_new(ItemDescription)
    end
  end

  describe "GET edit" do
    it "assigns the requested item_description as @item_description" do
      item_description = ItemDescription.create! valid_attributes
      get :edit, :id => item_description.id.to_s
      assigns(:item_description).should eq(item_description)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ItemDescription" do
        expect {
          post :create, :item_description => valid_attributes
        }.to change(ItemDescription, :count).by(1)
      end

      it "assigns a newly created item_description as @item_description" do
        post :create, :item_description => valid_attributes
        assigns(:item_description).should be_a(ItemDescription)
        assigns(:item_description).should be_persisted
      end

      it "redirects to the created item_description" do
        post :create, :item_description => valid_attributes
        response.should redirect_to(ItemDescription.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved item_description as @item_description" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemDescription.any_instance.stub(:save).and_return(false)
        post :create, :item_description => {}
        assigns(:item_description).should be_a_new(ItemDescription)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemDescription.any_instance.stub(:save).and_return(false)
        post :create, :item_description => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested item_description" do
        item_description = ItemDescription.create! valid_attributes
        # Assuming there are no other item_descriptions in the database, this
        # specifies that the ItemDescription created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ItemDescription.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => item_description.id, :item_description => {'these' => 'params'}
      end

      it "assigns the requested item_description as @item_description" do
        item_description = ItemDescription.create! valid_attributes
        put :update, :id => item_description.id, :item_description => valid_attributes
        assigns(:item_description).should eq(item_description)
      end

      it "redirects to the item_description" do
        item_description = ItemDescription.create! valid_attributes
        put :update, :id => item_description.id, :item_description => valid_attributes
        response.should redirect_to(item_description)
      end
    end

    describe "with invalid params" do
      it "assigns the item_description as @item_description" do
        item_description = ItemDescription.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemDescription.any_instance.stub(:save).and_return(false)
        put :update, :id => item_description.id.to_s, :item_description => {}
        assigns(:item_description).should eq(item_description)
      end

      it "re-renders the 'edit' template" do
        item_description = ItemDescription.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemDescription.any_instance.stub(:save).and_return(false)
        put :update, :id => item_description.id.to_s, :item_description => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested item_description" do
      item_description = ItemDescription.create! valid_attributes
      expect {
        delete :destroy, :id => item_description.id.to_s
      }.to change(ItemDescription, :count).by(-1)
    end

    it "redirects to the item_descriptions list" do
      item_description = ItemDescription.create! valid_attributes
      delete :destroy, :id => item_description.id.to_s
      response.should redirect_to(item_descriptions_url)
    end
  end

end
